plataforma/apps/cobros/urls.py
from django.urls import path

from apps.cobros.views.cobros.views_nod.views_nod import AplicarNuevaOD
from apps.cobros.views.cobros.views_pagos import *
from apps.cobros.views.cobros.views_reportes import *
from apps.cobros.views.cobros.views_rtt.views_rtt import *
from apps.ventas.views.solicitudes.views_proceso import SolicitudesProcesoEdit

app_name = 'cobros'

urlpatterns = [
    path('lista_clientes/', ListaClientesCobros.as_view(), name='lista_clientes'),
    path('morosidad/', Morosidad.as_view(), name='morosidad_clientes'),
    path('lista_clientes/<int:pk>/', CobroCliente.as_view(), name='cobro_cliente'),
    path('agregar_ant/', AgregarClienteAntiguo.as_view(), name='agregar_antiguo'),
    path('editar_cliente/<int:pk>/<str:tipo>/', EditClienteAntiguo.as_view(), name='editar_antiguo'),
    path('ver_cliente/<int:pk>/<str:tipo>/', VerClienteCobros.as_view(), name='ver_cliente_cobros'),
    # Editar Info de cliente 'nuevo' Aprobado
    path('editar_cliente/aprobado/<int:pk>/<str:info>/', SolicitudesProcesoEdit.as_view(), name='edit_info_cliente_nuevo'),
    # Transacciones
    path('info_tr/<int:pk>/<str:tipo>/', InfoTransacciones.as_view(), name='info_transacciones'),
    path('lista_tr/', ListaTransacciones.as_view(), name='info_transacciones'),
    # Reportes Cobros
    path('estado_cuenta/<int:pk>/<str:tipo>/', EstadoCuenta.as_view(), name='estado_cuenta'),
    path('desglose_prepago/<int:pk>/<str:tipo>/', DesglosePrepago.as_view(), name='desglose_prepago'),
    # Clientes cancelación anticipada
    path('prepago_cliente/<int:pk>/<str:tipo>/', AplicarPrepago.as_view(), name='aplicar_prepago'),
    # Proceso reestructuración
    path('reestructurar/<int:pk>/<str:tipo>/', ReestructurarCredito.as_view(), name='reestructurar_2'),
    # Clientes reestructuración
    path('lista_clientes_rtt/', ListaClientesRtt.as_view(), name='clientes_rtt'),
    path('lista_clientes_rtt/<int:pk>/', CobroClienteRtt.as_view(), name='cobro_cliente_rtt'),
    # Clientes Nueva OD
    # path('lista_clientes_rtt/', ListaClientesRtt.as_view(), name='clientes_rtt'),
    path('cliente_nueva_OD/<int:pk>/', AplicarNuevaOD.as_view(), name='nueva_OD'),
]

# r'^solicitudes/agregar/(?P<class>\d+)/$' | r'^editar_antiguo/<int:pk>/(?P<class>\d+)/$'

plataforma/plataforma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.login.views import Login
from apps.ventas.views.dashboard.views import Dashboard
from plataforma.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('apps.login.urls')),
    path('inicio/', Dashboard.as_view(),  name='dashboard'),
    path('cobros/', include('apps.cobros.urls')),
    path('formulario/', include('apps.formulario.urls')),
    path('prestamos/', include('apps.prestamos.urls')),
    path('ventas/', include('apps.ventas.urls')),
    path('reportes/', include('apps.reportes.urls')),
]

if DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/apps/cobros/models.py
import os

from django.db import models
from django.forms import model_to_dict
from django.utils import timezone as tz
from django.utils.translation import gettext_lazy as _

# Create your models here.
from apps.cobros.choices import *
from apps.formulario.models import TipoIngreso, TipoDocumento, Genero, Provincia, Distrito, Corregimiento, Motivo, \
    EstadoCivil, Dependientes, IngresosExtra, Escolaridad, PEP
from apps.prestamos.models import Aprobado
from apps.ventas.models import Empresa


class ClasePago(models.Model):
    clase_pago = models.CharField(_('clase pago'), max_length=30)

    def __str__(self):
        salida = self.clase_pago
        return salida


class Bancos(models.Model):
    nombre = models.CharField(_('nombre'), max_length=40)
    num_cuenta = models.CharField(_('num cuenta'), max_length=60, null=True, blank=True)
    telefono = models.CharField(_('telefono'), max_length=15, null=True, blank=True)
    nombre_cuenta = models.CharField(_('num cuenta'), max_length=60, null=True, blank=True)

    def toJSON(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        salida = self.nombre
        return salida


class ClienteAntiguo(models.Model):
    creado_el = models.DateTimeField(_('creado el'), null=False, blank=True, default=tz.now)  #
    fecha_ingreso = models.DateTimeField(auto_now_add=True)  #
    monto = models.CharField(_('monto'), null=False, blank=False, max_length=20)  #
    plazo = models.CharField(_('plazo meses'), null=False, blank=False, max_length=40)  #
    compra_saldo = models.CharField(_('cancelaciones'), null=True, blank=True, max_length=200)  #
    promotor = models.CharField(_('promotor'), max_length=100, null=True, blank=True)  #
    c_promotor = models.CharField(_('c promotor'), max_length=40, null=True, blank=True)  #
    s_descuento = models.CharField(_('s descuento'), max_length=40, null=True, blank=True)  #
    fecha_ini = models.DateField(_('f inicio'), null=False, blank=False)  #
    f_contrato = models.DateField(_('f contrato'), null=True, blank=True)  #
    ob_contrato = models.CharField(_('ob contrato'), null=True, blank=True, max_length=20)  #
    c_cierre = models.CharField(_('c cierre'), max_length=40, null=True, blank=True)  #
    tipo_ingreso = models.ForeignKey(TipoIngreso, on_delete=models.SET_NULL, null=True)  #
    salario = models.DecimalField(_('salario'), max_digits=6, decimal_places=2, null=False, blank=False)  #
    empresa_1 = models.CharField(_('empresa'), max_length=50, null=True, blank=True)  #
    empresa_2 = models.ForeignKey(Empresa, max_length=50, on_delete=models.SET_NULL, null=True, blank=True)  #
    nombre_1 = models.CharField(_('nombre 1'), max_length=40, null=False, blank=False)  #
    nombre_2 = models.CharField(_('nombre 2'), max_length=40, null=True, blank=True)  # Puede estar en blanco  #
    apellido_1 = models.CharField(_('apellido 1'), max_length=40, null=False, blank=False)  #
    apellido_2 = models.CharField(_('apellido 2'), max_length=40, null=True, blank=True)  #
    genero = models.ForeignKey(Genero, null=True, blank=True, on_delete=models.SET_NULL)  #
    f_nacimiento = models.DateField(_('f nacimiento'))  #
    tipo_doc = models.ForeignKey(TipoDocumento, on_delete=models.SET_NULL, null=True)  #
    nacionalidad = models.CharField(_('nacionalidad'), max_length=50, null=True, blank=True)  #
    dni = models.CharField(_('dni'), max_length=20, null=False, blank=False)  #
    email_1 = models.EmailField(_('email 1'), max_length=254, null=True, blank=True)  #
    celular = models.IntegerField(_('celular'), null=False, blank=False)  #
    telefono = models.IntegerField(_('telefono'), null=True, blank=True)  # Disponible sólo en antiguo
    notas = models.CharField(_('notas'), max_length=1000, null=True, blank=True)  #
    notas_user = models.CharField(_('notas'), max_length=1000, null=True, blank=True)  #
    check_cumplimiento = models.CharField(_('check cumplimiento'), null=True, blank=True, max_length=40,
                                          default='No verificado')  # S. antiguo
    id_cliente = models.CharField(_('id cliente'), max_length=15, null=True, blank=True)  # Temporal
    estatus = models.CharField(_('estatus'), max_length=50, default='Activo')  #
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True, blank=True)  #
    distrito = models.ForeignKey(Distrito, on_delete=models.SET_NULL, null=True, blank=True)  #
    corregimiento = models.ForeignKey(Corregimiento, on_delete=models.SET_NULL, null=True, blank=True)  #
    direccion = models.CharField(_('dir_cliente'), max_length=250, null=True, blank=True)  #
    creado_por = models.CharField(_('creado por'), max_length=40, null=True, blank=True)  # Eq. visto por
    num_contrato = models.CharField(_('id contrato'), max_length=30, null=True, blank=True)  #
    fecha_ini_OD = models.DateField(_('f inicio OD'), null=True, blank=True)  #

    # Complementos Aprobación
    orden_descuento = models.FileField(_('orden descuento'), upload_to='Aprobados/orden_descuento/%Y/%m/%d', null=True,
                                       blank=True)
    contrato = models.FileField(_('contrato'), upload_to='Aprobados/contrato/%Y/%m/%d', null=True, blank=True)
    pagare = models.FileField(_('pagare'), upload_to='Aprobados/pagare/%Y/%m/%d', null=True, blank=True)
    conoce_cliente = models.FileField(_('conoce cliente'), upload_to='Aprobados/conoce_cliente/%Y/%m/%d', null=True,
                                      blank=True)
    f_1 = models.FileField(_('f 1'), upload_to='Aprobados/F_1/%Y/%m/%d', null=True, blank=True)

    # Complementos PreAprobado
    dependientes = models.ForeignKey(Dependientes, on_delete=models.SET_NULL, null=True)
    motivo = models.ForeignKey(Motivo, on_delete=models.SET_NULL, null=True, blank=True)
    e_civil = models.ForeignKey(EstadoCivil, on_delete=models.SET_NULL, null=True)
    in_extras = models.ForeignKey(IngresosExtra, on_delete=models.SET_NULL, null=True)
    estudios = models.ForeignKey(Escolaridad, on_delete=models.SET_NULL, null=True)
    p_expuesto = models.ForeignKey(PEP, on_delete=models.SET_NULL, null=True)
    terms = models.BooleanField(_('terms'), default=False)
    apc = models.BooleanField(_('apc'), default=False)

    # Documentos PreAprobado
    DNI_img = models.FileField(_('dni img'), upload_to='DNI/%Y/%m/%d', null=True, blank=True)
    carta_trabajo_img = models.FileField(_('carta trabajo'), upload_to='carta_trabajo/%Y/%m/%d', null=True, blank=True)
    talonario_1_img = models.FileField(_('talonario 1'), upload_to='talonario_1/%Y/%m/%d', null=True, blank=True)
    talonario_2_img = models.FileField(_('talonario 2'), upload_to='talonario_2/%Y/%m/%d', null=True, blank=True)
    ficha_img = models.FileField(_('ficha'), upload_to='ficha_seguro/%Y/%m/%d', null=True, blank=True)
    recibo_img = models.FileField(_('recibo'), upload_to='recibo_publico/%Y/%m/%d', null=True, blank=True)
    carta_saldo_img = models.FileField(_('carta_saldo'), upload_to='carta_saldo/%Y/%m/%d', null=True, blank=True)
    file_apc = models.FileField(_('file apc'), upload_to='APC/%Y/%m/%d', null=True, blank=True)
    notas_cumplimiento = models.CharField(_('notas cumplimiento'), max_length=1000, null=True, blank=True)
    notas_gerencia = models.CharField(_('notas gerencia'), max_length=1000, null=True, blank=True)
    notas_cobros = models.CharField(_('notas gerencia'), max_length=1000, null=True, blank=True)

    def __str__(self):
        salida = self.nombre_1 + ' ' + self.apellido_1
        return salida

    # Docs PreAprobado

    def dni_name(self):
        return os.path.basename(self.DNI_img.name)

    def carta_trabajo_name(self):
        return os.path.basename(self.carta_trabajo_img.name)

    def talonario_1_name(self):
        return os.path.basename(self.talonario_1_img.name)

    def talonario_2_name(self):
        return os.path.basename(self.talonario_2_img.name)

    def ficha_name(self):
        return os.path.basename(self.ficha_img.name)

    def recibo_name(self):
        return os.path.basename(self.recibo_img.name)

    def carta_saldo_name(self):
        return os.path.basename(self.carta_saldo_img.name)

    def file_apc_name(self):
        return os.path.basename(self.file_apc.name)

    # Docs Aprobado

    def od_name(self):
        return os.path.basename(self.orden_descuento.name)

    def f1_name(self):
        return os.path.basename(self.f_1.name)

    def contrato_name(self):
        return os.path.basename(self.contrato.name)

    def pagare_name(self):
        return os.path.basename(self.pagare.name)

    def c_cliente_name(self):
        return os.path.basename(self.conoce_cliente.name)


class Desembolso(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    cliente = models.ForeignKey(Aprobado, null=True, blank=True, on_delete=models.CASCADE)
    cliente_ant = models.ForeignKey(ClienteAntiguo, null=True, blank=True, on_delete=models.CASCADE)
    lista_pagos = models.CharField(max_length=1000, null=True, blank=True)
    lista_cambios = models.CharField(max_length=1500, null=True, blank=True)
    ajuste = models.CharField(_('ajuste'), max_length=100, default='No requerido')
    notas = models.CharField(_('notas'), max_length=1000, null=True, blank=True)
    notas_user = models.CharField(_('notas'), max_length=1000, null=True, blank=True)  #
    # Cancelado: cuotas terminadas, Reestructurado: estatus con nuevos parámetros de cálculo
    estatus = models.CharField(_('estatus'), max_length=50,
                               default='Activo')  # Activo, cancelado, vencido, pagado, anticipado**
    # Comprobante ACH de la transferencia
    comprobante = models.FileField(_('comprobante'), upload_to='Aprobados/comprobante/%Y/%m/%d', null=True, blank=True)
    ajuste_letra = models.DecimalField(_('ajuste letra'), max_digits=5, decimal_places=2, null=True, blank=True)

plataforma/apps/cobros/templates/cobros/clientes_rtt/lista_rtt.html
{% extends 'base_datatable.html' %}
{% load static %}

{% block script_head %}
    <!-- FormValidation -->
    <link rel="stylesheet" href="{% static 'lib/formvalidation-dist-v1.8.0/dist/css/formValidation.min.css' %}">
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/es6-shim.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/FormValidation.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/plugins/Bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/plugins/Recaptcha.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/locales/es_ES.min.js' %}"></script>

{% endblock %}

{% block table_header %}

    <span class="h4"><b>{{ card_title }}</b></span>

{% endblock %}

{########################}

{% block table_body %}

    <table id="lista_cobros" class="table table-hover table-head-fixed" style="width: 100%">
        {#                            <table class="table" id="tabla_1">#}
        <thead>
        <tr>
            <th scope="col" style="width: 10%;">Contrato</th>
            <th scope="col" style="width: 11%;">Nombre</th>
            <th scope="col" style="width: 11%;">Apellido</th>
            <th scope="col" style="width: 8%;">Atraso</th>
            <th scope="col" style="width: 5%;">Clase</th>
            <th scope="col" style="width: 15%;">Tipo ingreso</th>
            <th scope="col" style="width: 15%;">Capital</th>
            <th scope="col" style="width: 5%;">Plazo</th>
            <th scope="col" style="width: 10%;">Celular</th>
            <th scope="col" style="width: 10%;">Opciones</th>
            {#                                    <th scope="col">Cotizar</th>#}
        </tr>
        </thead>
        <tbody>

        </tbody>
        <tfoot>
        <tr>
            <th scope="col" style="width: 10%;"></th>
            <th scope="col" style="width: 11%;"></th>
            <th scope="col" style="width: 11%;"></th>
            <th scope="col" style="width: 8%;"></th>
            <th scope="col" style="width: 5%;"></th>
            <th scope="col" style="width: 15%;">Tipo ingreso</th>
            <th scope="col" style="width: 15%;"></th>
            <th scope="col" style="width: 5%;"></th>
            <th scope="col" style="width: 10%;"></th>
            <th scope="col" style="width: 10%;"></th>
        </tr>
        </tfoot>
    </table>


{% endblock %}

{########################}

{% block table_footer %}

    <!-- Button trigger modal -->
    <div class="row">
        <div class="col-auto mb-1">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_cliente_modal">
                <i class="fas fa-user-plus"></i> Agregar cliente existente
            </button>
        </div>
        <div class="col-auto">
            <!-- Button formulario completo -->
            <a type="button" class="btn btn-warning" href="{% url 'cobros:agregar_antiguo' %}">
                <i class="fas fa-user-plus"></i> Agregar cliente existente (Formulario completo)
            </a>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade bd-example-modal-lg" id="add_cliente_modal" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-dark">
                    <h5 class="modal-title" id="exampleModalLongTitle"><i style="color: dodgerblue"
                                                                          class="fas fa-user-plus"></i><b> Agregar
                        cliente</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="cliente_antiguo">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="container container-fluid text-dark">
                            <h5 class="text-center"><b>Info. personal:</b></h5>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_nombre_1">Primer nombre <span class="text-danger">*</span>:</label>
                                    {{ form.nombre_1 }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_nombre_2">Segundo nombre:</label>
                                    {{ form.nombre_2 }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_apellido_1">Primer apellido <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.apellido_1 }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_apellido_2">Segundo apellido:</label>
                                    {{ form.apellido_2 }}
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_tipo_doc">Tipo de documento <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.tipo_doc }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_dni">DNI <span class="text-danger">*</span>:</label>
                                    {{ form.dni }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_f_nacimiento">Fecha de nacimiento:<span
                                            class="text-danger">*</span>:</label>
                                    {{ form.f_nacimiento }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_nacionalidad">Nacionalidad:</label>
                                    {{ form.nacionalidad }}
                                </div>
                            </div>
                            <hr>
                            <h5 class="text-center"><b>Info. de contacto:</b></h5>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_celular">Celular <span class="text-danger">*</span>:</label>
                                    {{ form.celular }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_telefono">Teléfono:</label>
                                    {{ form.telefono }}
                                </div>
                                <div class="col-sm-6">
                                    <label for="id_email_1">Email:</label>
                                    {{ form.email_1 }}
                                </div>
                            </div>
                            <hr>
                            <h5 class="text-center"><b>Info. del crédito:</b></h5>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_monto">Monto <span class="text-danger">*</span>:</label>
                                    {{ form.monto }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_plazo_meses">Plazo (meses) <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.plazo }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_f_inicio">F. inicio contrato <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.fecha_ini }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_f_inicio_OD">F. inicio O.D. <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.fecha_ini_OD }}
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_f_contrato">Fecha contrato <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.f_contrato }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_cancelaciones">Cancelaciones:</label>
                                    {{ form.compra_saldo }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_promotor">Promotor:</label>
                                    {{ form.promotor }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_ob_contrato">Obligación contrato <span class="text-danger">*</span>:</label>
                                    {{ form.ob_contrato }}
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-sm-3">
                                    <label for="id_c_cierre">Ajuste de C. cierre:</label>
                                    {{ form.c_cierre }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_id_contrato">ID. Contrato <span class="text-danger">*</span>:</label>
                                    {{ form.num_contrato }}
                                </div>
                            </div>
                            <hr>
                            <h5 class="text-center"><b>Info. laboral:</b></h5>
                            <div class="row form-group">
                                <div class="col-sm-6">
                                    <label for="id_empresa_2">Empresa: <span class="text-danger">*</span>:</label>
                                    {{ form.empresa_2 }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_salario">Salario:</label>
                                    {{ form.salario }}
                                </div>
                                <div class="col-sm-3">
                                    <label for="id_tipo_ingreso">Tipo de ingreso: <span
                                            class="text-danger">*</span>:</label>
                                    {{ form.tipo_ingreso }}
                                </div>
                            </div>
                            <hr>
                            <div class="col-sm-12">
                                <label for="id_notas">Notas:</label>
                                {{ form.notas }}
                            </div>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" form="cliente_antiguo" class="btn btn-primary"><i
                            class="far fa-plus-square"></i> Agregar
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts_java %}
    <script src="{% static 'cobros/js_rtt/lista_clientes_rtt.js' %}"></script>

{% endblock %}