plataforma/apps/prestamos/urls.py
from django.urls import path

from apps.cobros.views.cobros.views_pagos import VerClienteCobros
from apps.prestamos.views.aprobaciones.cotizador_views import *
from apps.prestamos.views.aprobaciones.docs_views import *
from apps.prestamos.views.aprobaciones.views import *
from apps.prestamos.views.aprobaciones.views_ajuste_creditos import *
from apps.prestamos.views.clientes.views import ListaClientes
from apps.prestamos.views.desembolso.views import *
from apps.prestamos.views.saldos.views import CartasSaldo
from apps.ventas.views.solicitudes.views_proceso import SolicitudesProcesoEdit

app_name = 'prestamos'

urlpatterns = [
    # Aprobación
    path('aprobacion/', AprobacionClientes.as_view(), name='aprobacion_clientes'),
    path('aprobados/', ListaAprobados.as_view(), name='lista_aprobados'),
    path('aprobacion/ver/<int:pk>/', AprobacionVer.as_view(), name='aprobacion_ver'),
    path('aprobados/ver/<int:pk>/', AprobadosVer.as_view(), name='aprobados_ver'),
    # Desembolsos
    path('aprobados/desembolsos/', ListaDesembolsosPendientes.as_view(), name='lista_desembolsos_p'),
    path('aprobados/desembolsos/<int:pk>/', RegistrarDesembolso.as_view(), name='aprobados_ver'),
    # Lista de clientes
    path('clientes/', ListaClientes.as_view(), name='lista_clientes'),
    # Cartas de saldo
    path('cartasaldo/', CartasSaldo.as_view(), name='cartas_saldo'),
    # path('prestamos/lista_clientes/', FormularioView.as_view(), name='formulario_create'),
    # Documentos
    path('aprobados/cotizacion/<int:pk>/<str:tipo>/', CotizacionAprobado.as_view(), name='aprobado_cotizacion'),
    path('aprobados/detalles/<int:pk>/<str:tipo>/', DesgloseAprobado.as_view(), name='aprobado_desglose'),
    path('aprobados/orden_descuento/<int:pk>/', OrdenDescuento.as_view(), name='orden_descuento'),
    path('aprobados/contrato_cliente/<int:pk>/', ContratoCliente.as_view(), name='contrato_cliente'),
    path('aprobados/pagare_cliente/<int:pk>/', PagareCliente.as_view(), name='pagare_cliente'),
    # Editar info de Aprobado
    path('aprobados/edit/<int:pk>/<str:info>/', SolicitudesProcesoEdit.as_view(), name='edit_info_cliente'),
    # Ajustes Préstamos clientes
    path('aprobados/lista_ajuste/', ListaAprobacionesContratos.as_view(), name='ajustes_aprobaciones'),
    path('aprobados/lista_ajuste/<int:pk>/<str:tipo>/', VerAprobados.as_view(), name='info_cliente'),
    path('aprobados/crear_desembolso/<int:pk>/', CrearDesembolso.as_view(), name='crear_desembolso'),
    # Operaciones
    path('aprobados/lista_operaciones/', ListaOperaciones.as_view(), name='lista_operaciones'),
    path('aprobados/lista_operaciones/<int:pk>/', Operaciones.as_view(), name='operacion_cliente'),
    # Clientes desembolsados activos
    path('aprobados/desembolsados/<int:pk>/<str:tipo>/', VerClienteCobros.as_view(), name='info_desembolsado'),
]

plataforma/plataforma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.login.views import Login
from apps.ventas.views.dashboard.views import Dashboard
from plataforma.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('apps.login.urls')),
    path('inicio/', Dashboard.as_view(),  name='dashboard'),
    path('cobros/', include('apps.cobros.urls')),
    path('formulario/', include('apps.formulario.urls')),
    path('prestamos/', include('apps.prestamos.urls')),
    path('ventas/', include('apps.ventas.urls')),
    path('reportes/', include('apps.reportes.urls')),
]

if DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/apps/prestamos/models.py
import os

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone as tz

# Create your models here.
from apps.prestamos.choices import tipo_cuenta_dic
from apps.ventas.models import PreAprobado
from apps.cobros.choices import *


class BancoCliente(models.Model):
    nombre_banco = models.CharField(_('nombre banco'), max_length=40)
    telefono = models.CharField(_('telefono'), max_length=10, null=True, blank=True)

    def __str__(self):
        return self.nombre_banco


class Aprobado(models.Model):
    creado_el = models.DateTimeField(_('creado el'), null=True, blank=True, default=tz.now)  #
    fecha_ingreso = models.DateTimeField(auto_now_add=True)  #
    cliente = models.ForeignKey(PreAprobado, on_delete=models.CASCADE, null=False, blank=False, related_name='aprobado')  #
    monto = models.CharField(_('monto'), max_length=10, null=False, blank=False)  #
    plazo = models.CharField(_('plazo'), max_length=5, null=False, blank=False)  #
    fecha_ini = models.CharField(_('fecha inicio'), max_length=20, null=False, blank=False)  #
    f_contrato = models.DateField(_('f contrato'), null=True, blank=True)  #
    ob_contrato = models.CharField(_('ob contrato'), null=True, blank=True, max_length=20)  #
    c_cierre = models.CharField(_('c cierre'), max_length=10, null=True, blank=True)  #
    compra_saldo = models.CharField(_('compra saldo'), max_length=100, null=True, blank=True)  #
    c_promotor = models.CharField(_('c promotor'), max_length=10, null=True, blank=True)  #
    s_descuento = models.CharField(_('s descuento'), max_length=10, null=True, blank=True)  #
    estatus = models.CharField(_('estatus'), max_length=30, null=False, blank=False)  #
    aviso_cliente = models.CharField(_('aviso cliente'), max_length=10, null=True, blank=True)  # Sólo aprobaciones
    orden_descuento = models.FileField(_('orden descuento'), upload_to='Aprobados/orden_descuento/%Y/%m/%d', null=True,
                                       blank=True)  #
    contrato = models.FileField(_('contrato'), upload_to='Aprobados/contrato/%Y/%m/%d', null=True, blank=True)  #
    pagare = models.FileField(_('pagare'), upload_to='Aprobados/pagare/%Y/%m/%d', null=True, blank=True)  #
    conoce_cliente = models.FileField(_('conoce cliente'), upload_to='Aprobados/conoce_cliente/%Y/%m/%d', null=True,
                                      blank=True)  #
    f_1 = models.FileField(_('f 1'), upload_to='Aprobados/F_1/%Y/%m/%d', null=True, blank=True)  #
    notas = models.CharField(_('notas'), max_length=1000, null=True, blank=True)  #
    notas_user = models.CharField(_('notas'), max_length=1000, null=True, blank=True)  #
    num_contrato = models.CharField(_('num contrato'), max_length=20, null=True, blank=True)  #
    fecha_ini_OD = models.DateField(_('f inicio OD'), null=True, blank=True)  # Fecha acordada con planilla
    # Operaciones: None, pend_desembolso, reg_desembolso, desembolsado
    operaciones = models.CharField(_('operaciones'), max_length=30, null=True, blank=True)
    email_conf = models.FileField(_('email conf'), upload_to='Aprobados/email_conf/%Y/%m/%d', null=True, blank=True)  #

    def __str__(self):
        return str(self.cliente)

    def od_name(self):
        return os.path.basename(self.orden_descuento.name)

    def f1_name(self):
        return os.path.basename(self.f_1.name)

    def contrato_name(self):
        return os.path.basename(self.contrato.name)

    def pagare_name(self):
        return os.path.basename(self.pagare.name)

    def c_cliente_name(self):
        return os.path.basename(self.conoce_cliente.name)

    def email_conf_name(self):
        return os.path.basename(self.email_conf.name)

#  Estatus: 'Sin O.D.', 'O.D. recibida y verificada', 'Documentación firmada', 'Desembolsado'

class InfoBancariaCliente(models.Model):
    cliente = models.ForeignKey(Aprobado, on_delete=models.CASCADE)
    nombre_cuenta = models.CharField(_('nombre cuenta'), max_length=100)
    numero_cuenta = models.CharField(_('numero cuenta'), max_length=50)
    banco = models.ForeignKey(BancoCliente, null=True, blank=True, on_delete=models.SET_NULL)
    tipo_cuenta = models.CharField(_('tipo cuenta'), max_length=20, choices=tipo_cuenta_dic)
    notas = models.CharField(_('notas'), max_length=1500, null=True, blank=True)

    def __str__(self):
        return self.cliente

plataforma/apps/prestamos/forms.py
from apps.cobros.choices import *
from apps.cobros.models import Desembolso
from apps.prestamos.models import Aprobado, InfoBancariaCliente
from apps.ventas.models import PreAprobado, Empresa
from django.forms import *
from django import forms


class AprobacionesVer(ModelForm):
    tipo_doc = TextInput()

    class Meta:
        model = PreAprobado
        fields = '__all__'
        # fields = ['notas', 'check_1', 'check_2', 'check_3']

        widgets = {
            'notas': Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Escriba sus comentarios aquí.',
                    'autocomplete': 'off',
                    'rows': '5',
                    'cols': '150'
                }
            ),
            'check_1': CheckboxInput(
                attrs={
                    'type': 'checkbox',
                    'class': 'custom-control-input',
                    'onchange': 'ventas();'
                }
            ),
            'check_2': CheckboxInput(
                attrs={
                    'type': 'checkbox',
                    'class': 'custom-control-input',
                    'onchange': 'descartar();'
                }
            ),
            'check_3': CheckboxInput(
                attrs={
                    'type': 'checkbox',
                    'class': 'custom-control-input',
                    'onchange': 'cumplimiento();'
                }
            ),
            'monto': NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'plazo_meses': NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


class ClientesAprobadosVer(ModelForm):
    class Meta:
        model = Aprobado
        fields = ['orden_descuento', 'f_1', 'contrato', 'pagare', 'fecha_ini_OD']
        # fields = ['notas', 'check_1', 'check_2', 'check_3']

        widgets = {
        }


class CuentaBancoCliente(ModelForm):
    class Meta:
        model = InfoBancariaCliente

        fields = '__all__'

        widgets = {
            'nombre_cuenta': TextInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': 'Ingrese el nombre de la cuenta',
                    'autocomplete': 'off'
                }
            ),
            'numero_cuenta': TextInput(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': 'Ingreso el número de cuenta',
                    'autocomplete': 'off'
                }
            ),
            'banco': Select(
                attrs={
                    'class': 'form-control form-control-sm',
                }
            ),
            'tipo_cuenta': Select(
                attrs={
                    'class': 'form-control form-control-sm',
                }
            ),
            'notas': Textarea(
                attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': 'Escriba sus observaciones aquí',
                    'rows': '2',
                    'cols': '150'
                }
            )
        }


class FormAjustes1(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            # form.field.widget.attrs['class'] = 'form-control'
            form.field.widget.attrs['autocomplete'] = 'off'

    # c_cierre = forms.ChoiceField(choices=c_cierre_dic, required=False)

    class Meta:
        model = PreAprobado
        fields = '__all__'

        # widgets = {}


class FormAjustes2(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            # form.field.widget.attrs['class'] = 'form-control'
            form.field.widget.attrs['autocomplete'] = 'off'

    # c_cierre = forms.ChoiceField(choices=c_cierre_dic, required=False)

    class Meta:
        model = Aprobado
        fields = '__all__'

        # widgets = {}


class FormCrearDesembolso(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            if form.name == 'cliente':
                form.field.widget.attrs['class'] = 'form-control select2'
                # form.field.widget.attrs['disabled'] = ''
            else:
                form.field.widget.attrs['class'] = 'form-control'
            form.field.widget.attrs['autocomplete'] = 'off'

    c_promotor = forms.ChoiceField(choices=c_promotor_dic, required=False)
    s_descuento = forms.ChoiceField(choices=s_descuento_dic, required=False)
    c_cierre = forms.ChoiceField(choices=c_cierre_dic, required=False)
    estatus = forms.ChoiceField(choices=estatus_dic, required=True)

    class Meta:
        model = Aprobado
        # exclude = ('created_date', 'cliente_ant', 'lista_pagos', 'lista_cambios', 'estatus', 'comprobante',)
        fields_1 = ('cliente', 'monto', 'plazo', 'fecha_ini', 'f_contrato', 'fecha_ini_OD', 'ob_contrato')
        fields_2 = ('c_cierre', 'compra_saldo', 'c_promotor', 's_descuento', 'estatus', 'num_contrato', 'creado_el')
        fields = fields_1 + fields_2


class FormRegistroEmpresa(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['class'] = 'form-control select2'
            form.field.widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = PreAprobado
        # exclude = ('created_date', 'cliente_ant', 'lista_pagos', 'lista_cambios', 'estatus', 'comprobante',)
        fields = ('empresa_2',)

plataforma/apps/prestamos/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from apps.formulario.models import Formulario


def ViewTest(request):
    data = {
        'title': 'Listado de Categorías',
    }
    return render(request, '1_solicitudes_rev.html', data)

plataforma/apps/prestamos/views/clientes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import ListView

from apps.formulario.models import Formulario


class ListaClientes(LoginRequiredMixin, ListView):
    model = Formulario
    template_name = 'prestamos/1_lista_clientes.html'

    @staticmethod
    def post(request, *args, **kwargs):
        data = {'test': 'Plataforma'}
        print(request.POST)
        # cat = Formulario.objects.get(pk=request.POST['id'])
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = SolicitudRevisada()
        context['section_name'] = 'Préstamos'
        context['card_title'] = 'Lista de clientes'
        context['active_prestamos'] = 'active'
        context['active_prestamos_clientes'] = 'active'
        return context

plataforma/apps/prestamos/views/saldos/views.py
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from apps.formulario.models import Formulario


class CartasSaldo(ListView):
    model = Formulario
    template_name = 'prestamos/3_carta_saldo.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {'test': 'Plataforma'}
        print(request.POST)
        # cat = Formulario.objects.get(pk=request.POST['id'])
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = SolicitudRevisada()
        context['section_name'] = 'Préstamos'
        context['card_title'] = 'Solicitudes pre-aprobadas'
        context['active_prestamos'] = 'active'
        context['active_prestamos_cartasaldo'] = 'active'
        return context

plataforma/apps/prestamos/templates/prestamos/ajustes_rc/crear_desembolso.html
{% extends 'base_1.html' %}
{% load static %}

{% block script_head %}

    <!-- FormValidation -->
    <link rel="stylesheet" href="{% static 'lib/formvalidation-dist-v1.8.0/dist/css/formValidation.min.css' %}">
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/es6-shim.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/FormValidation.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/plugins/Bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/plugins/Recaptcha.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-dist-v1.8.0/dist/js/locales/es_ES.min.js' %}"></script>

{% endblock %}

{% block content_base %}

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Default box 1 -->
                    <div class="card" style="background-color:#e6ffde;">
                        <div class="card-header bg-gradient-gray-dark border border-dark">
                            <h6 class="card-title text-lg"><strong>{{ card_title }} <span
                                    style="color: #FF8C33;">{{ num_solicitud }}</span></strong>
                            </h6>
                        </div>
                        <form id="desembolso">
                            {% csrf_token %}
                            <div class="card-body border border-dark">
                                <div class="row mb-2">
                                    <div class="col-6">
                                        <label for="id_cliente">Nombre cliente aprobado</label>
                                        {{ form.cliente }}
                                    </div>
                                    <div class="col-2">
                                        <label for="id_monto">Monto</label>
                                        {{ form.monto }}
                                    </div>
                                    <div class="col-2">
                                        <label for="id_plazo">Plazo</label>
                                        {{ form.plazo }}
                                    </div>
                                    <div class="col-2">
                                        <label for="id_fecha_ini">Fecha inicio</label>
                                        {{ form.fecha_ini }}
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-3">
                                        <label for="id_f_contrato">Fecha contrato</label>
                                        {{ form.f_contrato }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_f_contrato">Fecha inicio O.D.</label>
                                        {{ form.fecha_ini_OD }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_ob_contrato">Obligación de contrato</label>
                                        {{ form.ob_contrato }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_c_cierre">Comision de cierre</label>
                                        {{ form.c_cierre }}
                                    </div>

                                </div>
                                <div class="row mb-2">
                                    <div class="col-3">
                                        <label for="id_compra_saldo">Compra de saldo</label>
                                        {{ form.compra_saldo }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_c_promotor">Comision de promotor</label>
                                        {{ form.c_promotor }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_s_descuento">Servicio de descuento</label>
                                        {{ form.s_descuento }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_estatus">Estatus aprobación</label>
                                        {{ form.estatus }}
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-3">
                                        <label for="id_num_contrato">Num. de contrato</label>
                                        {{ form.num_contrato }}
                                    </div>
                                    <div class="col-3">
                                        <label for="id_num_contrato">Fecha Aprobación</label>
                                        {{ form.creado_el }}
                                    </div>
                                    {% if registro_empresa %}
                                        <div class="col-3">
                                            <label for="registro_empresa">Registro empresa</label>
                                            <span id="registro_empresa">{{ object.cliente.empresa_2 }}</span>
                                            <i class="fas fa-check fa-7x"></i>
                                        </div>
                                    {% else %}
                                        <div class="col-3">
                                            <label for="registro_empresa">Registro empresa</label>
                                            <i class="fas fa-times fa-2x danger"></i> {{ object.cliente.empresa_1 }}
                                        </div>
                                        <div class="col-3">
                                            <button type="button" class="btn btn-info" data-toggle="modal"
                                                    data-target="#registro_empresa">Registro empresa
                                            </button>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                        <!-- /.card-body -->
                        <div class="card-footer border border-dark bg-gradient-gray-dark">
                            <button form="desembolso" type="submit" class="btn btn-success border border-light">
                                Guardar cambios
                            </button>
                            <a class="btn btn-info" href="{% url 'prestamos:ajustes_aprobaciones' %}"> Regresar
                            </a>
                            {{ error }}
                        </div>
                        <!-- /.card-footer-->
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Registro Empresa -->
        <div class="modal fade" id="registro_empresa" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-gradient-dark">
                        <h5 class="modal-title" id="exampleModalLongTitle">Registro de empresa</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="reg_empresa_2">
                        {% csrf_token %}
                        <div class="modal-body">
                            <label for="id_empresa_2">Registro de empresa</label>
                            {{ form_empresa.empresa_2 }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="button" onclick="registro_empresa()" class="btn btn-primary"><i class="far fa-save"></i> Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts_java %}

    <script src="{% static 'prestamos/js/crear_desembolsos.js' %}"></script>

{% endblock %}

plataforma/apps/prestamos/templates/prestamos/ajustes_rc/detalles_cliente.html
{% extends 'base_1.html' %}
{% load static %}

{% block script_head %}

{% endblock %}

{% block content_base %}

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Default box 1 -->
                    <div class="card" style="background-color:#e6ffde;">
                        <div class="card-header bg-gradient-gray-dark border border-dark">
                            <h6 class="card-title text-lg"><strong>{{ card_title }} <span
                                    style="color: #FF8C33;">{{ num_solicitud }}</span></strong>
                            </h6>
                        </div>
                        <div class="card-body border border-dark">
                            {{ form.as_table }}

                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer border border-dark bg-gradient-gray-dark">
                            <a type="button" href="{% url 'prestamos:aprobacion_clientes' %}" id="regresar"
                               class="btn btn-warning border border-light"><i
                                    class="fas fa-undo-alt"></i> Regresar
                            </a>
                            <button form="aprobacion" type="submit" onclick="return aprobar()"
                                    class="btn btn-success border border-light"><i
                                    class="fas fa-thumbs-up"></i> Aprobar
                            </button>
                            <button form="aprobacion" type="submit" onclick="return rechazar()"
                                    class="btn btn-danger border border-light"><i
                                    class="fas fa-thumbs-down"></i> Rechazar
                            </button>
                            {{ error }}
                        </div>
                        <!-- /.card-footer-->
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts_java %}

{% endblock %}

plataforma/apps/prestamos/templates/prestamos/ajustes_rc/lista_aprobados.html
{% extends 'base_1.html' %}

{% load static %}

{% block listview %}
    <!-- Datatables -->
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>

    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'lib/DataTables_op/datatables.min.css' %}"/>

    <script type="text/javascript" src="{% static 'lib/DataTables_op/datatables.min.js' %}"></script>
{% endblock %}

{% block content_base %}

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Default box 1 -->
                    {% if request.user.username == 'vicente_rc' %}
                        <div class="card" style="background-color:#e6ffde;">
                            <div class="card-header bg-gradient-gray-dark border border-dark">
                                <h6 class="card-title text-lg"><strong>{{ card_title_1 }}</strong>
                                </h6>
                            </div>
                            <div class="card-body border border-dark">
                                <table class="table table-hover table-head-fixed" id="aprobados">
                                    <thead>
                                    <tr>
                                        <th scope="col" style="width: 10%;">ID</th>
                                        <th scope="col" style="width: 35%;">Nombre</th>
                                        <th scope="col" style="width: 10%;">Estatus</th>
                                        <th scope="col" style="width: 10%;">Monto</th>
                                        <th scope="col" style="width: 10%;">Plazo</th>
                                        <th scope="col" style="width: 15%;">Num. Contrato</th>
                                        <th scope="col" style="width: 10%;">Opciones</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>

                                </table>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer border border-dark bg-gradient-gray-dark">
                                <button type="button" id="update_cumplimiento" class="btn btn-info border border-light"><i
                                        class="fas fa-sync-alt"></i> Actualizar
                                </button>
                            </div>
                            <!-- /.card-footer-->
                        </div>
                    {% endif %}

                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'prestamos/js/tablas_ajustes.js' %}"></script>

{% endblock %}